### ISSUE TITLE
Splitting the Repositories

### ISSUE THREAD

**Issue by cekbote** [cekbote/coredns_ml_plugin#10]
@yongtang @greenpau

As we had discussed, we would be splitting up the project into different repositories under a single organisation named: mlbridge.
Under the mlbridge organisation we would have the following repositories
- mlbridge-flaskserver
- mlbridge-dashapplication
- mlbridge-plugin

Please let me know if you would like me to change some names

Moreover, I had a question: We would have to have a repo that ties all of this together i.e. a repo that has a readme (like we currently have). So what would that contain? A single readme that shows how the components are connected and then links to the other repositories?

**Comment by greenpau** [comment]
@cekbote , I would suggest the following:

* `mlbridge/mlbridge-middleware` or `mlbridge/middleware`: instead of `mlbridge-flaskserver`. What if tomorrow you use node.js or deno? :-)
* `mlbridge/mlbridge-ui` or `mlbridge/ui`: instead of `mlbridge-dashapplication`. What if tomorrow you learn React.js? ;-)
* `mlbridge/coredns-mlbridge` instead of mlbridge-plugin

Additionally, `mlbridge/docs`

**Comment by cekbote** [comment]
I have done something similar in the mlbridge organisation as we are porting our entire project there. 

I have used:
- mlbridge-machine_learning
- coredns-mlbridge
- mlbridge-middleware
- mlbridge-visualization_dashboard

Is this alright? 

Link to the organisation: https://github.com/mlbridge

**Comment by greenpau** [comment]
@cekbote , be consistent, use "-" ... `mlbridge-machine_learning` -> `mlbridge-machine-learning`

@cekbote , per `mlbridge-visualization_dashboard`. Do you think that `visualization` and `dashboard` are redundant?

**Comment by greenpau** [comment]
@cekbote , please put decent logo to the project! :-)

**Comment by cekbote** [comment]
> 
> 
> @cekbote , be consistent, use "-" ... `mlbridge-machine_learning` -> `mlbridge-machine-learning`
> 
> @cekbote , per `mlbridge-visualization_dashboard`. Do you think that `visualization` and `dashboard` are redundant?

I'll make the necessary changes:

- change mlbridge-machine_learning -> mlbridge-machine-learning
- change mlbridge-visualization_dashboard -> mlbridge-ui

**Comment by cekbote** [comment]
> 
> 
> @cekbote , please put decent logo to the project! :-)

For the logo, since its ML Bridge I was thinking of creating something similar to the golden gate bridge:

The logo would be similar to:

![index](https://user-images.githubusercontent.com/51071680/86786184-548c0c80-c081-11ea-8bbb-96de8f93a4f1.png)

It's just a concept but the bridge does look like an M and L together. (I would make the M and L prominent in the actual logo)
