### ISSUE TITLE
WhoIS API Integration

### ISSUE THREAD

**Issue by cekbote** [cekbote/coredns_ml_plugin#13]
@yongtang @greenpau

I have integrated the WhoIS API along with the visualization dashboard. A screenshot of the same can be seen below: 

![WhoIS](https://user-images.githubusercontent.com/51071680/86772698-205d1f80-c072-11ea-893b-6f98b8fd1247.jpg)

Please let me know your thoughts :)

**Comment by yongtang** [comment]
This looks really great 👍
