### ISSUE TITLE
Logo for the ML Bridge Organisation

### ISSUE THREAD

**Issue by cekbote** [cekbote/coredns_ml_plugin#15]
@yongtang @greenpau

Here is a logo for the ML Bridge organisation. Please let me know your thoughts. 

![mlbridgelogo3](https://user-images.githubusercontent.com/51071680/87145620-37e11600-c2c7-11ea-9ba7-34ab819486eb.png)
![mlbridgelogo2](https://user-images.githubusercontent.com/51071680/87145626-39aad980-c2c7-11ea-92e6-d30f4ef193f8.png)

**Comment by greenpau** [comment]
@cekbote , this looks awesome! ;-)

**Comment by yongtang** [comment]
Nice 👍 !
