### ISSUE TITLE
Using Prometheus in the plugin

### ISSUE THREAD

**Issue by cekbote** [cekbote/coredns_ml_plugin#3]
@yongtang @greenpau

I went through the documentation as well as implemented some very programs with Prometheus. It appears that it is kind of limited in its metric tracking (It takes only numeric data types). 

However, we would also like to know what websites are being queried and how many times (that way we could analyse if the ml algorithm is identifying some sites that are actually non-malicious). Therefore since the plugin is anyways communicating with the restful server (the flask python program) why not just use the flask python program to generate logs, tables, or live graphs so that the data could be recorded in a much better fashion?

If required I could create another local server specifically for displaying this data in a better fashion...

**Comment by yongtang** [comment]
@Chanakya-Ekbote This could be useful.

One thing that is quite unique about DNS, is that often DNS data logs becomes useful it is combined with time-series. However, DNS's time-series is often a per-IP or per-domain time-series. That means a per-IP or per-domain time-series database is needed. This might be less explored field but could be really useful for DNS.

**Comment by cekbote** [comment]
@yongtang Yes I was thinking of a per IP or per domain time series itself. I'll try to implement that on the Flask server and keep you updated. :)

**Comment by cekbote** [comment]
@yongtang I created a simple ML model, it can be found in this [repo](https://github.com/Chanakya-Ekbote/dns_alert_model)

To visualize what domain names are being queried and at what frequency, we can save all the domain names in a csv file, and then could be visualised using a python library known as [Dash](https://plotly.com/dash/). Would that be a good way to go about it ?

**Comment by yongtang** [comment]
@Chanakya-Ekbote The model looks promising 👍 .

I don't have enough experience with Dash but a visualization would be great

**Comment by cekbote** [comment]
@yongtang So what I've currently done is that the Flask Server is saving the date, time, IP address of the client, as well as the domain name of the website, queried, into a CSV file. I will now move on to graphing it using Dash.  However, this might take some time. Even I am not proficient with Dash however the documentation is very promising. It seems to have very good graphing capabilities and fits well into what we intend to do i.e. a DNS monitoring plugin.  

We could discuss a few things tomorrow:

- Training the model better with more data.
- Training the model on the cloud.
- The features the Dash server could have, such as:
  - Number of queries for a particular domain name per hour
  - A bar graph that denotes in batches of 10 the number of queries in a lifetime.
  - Some other ideas we come up with.
