### ISSUE TITLE
Creating a Historical Analysis Tool

### ISSUE THREAD

**Issue by cekbote** [cekbote/coredns_ml_plugin#6]
@yongtang Like we discussed before, we'd also be creating an analysis tool to visualize the results using Dash.

There were a few features that I would like to include. 
- A search bar to search for a domain name.
  - If its present in our database, we can display a line graph regarding queries per minute, per hour or per day as the user prescribes.
  - A table regarding the top IP addresses quering that domain.
- A bar graph that denotes the top malicious domains that are being queried.

Please let me know if that makes sense and also please feel free to add some other suggestions :)

**Comment by cekbote** [comment]
@yongtang Just an update. I created a mock up of the app (a very basic implementation using Dash). This isn't responsive currently. I'll probably add some css components to make it look better. Please let me know your thoughts.  
![Analysis_Tool_Mockup](https://user-images.githubusercontent.com/51071680/83904108-ec45c480-a77c-11ea-8928-fc3380c565e1.PNG)

Please let me know if you feel that I should add some other features. :)

**Comment by cekbote** [comment]
@yongtang I added some CSS elements, I think the App looks much better now. I'll move on to trying to incorporate Redis into python as I won't be able to add any functionality into the app without the time-series database. I'll come back to this once I incorporate Redis with Python. Please let me know your thoughts :).

![Analysis_2](https://user-images.githubusercontent.com/51071680/83943380-24024a00-a819-11ea-9873-0a62f359ee63.PNG)

**Comment by yongtang** [comment]
@chanakyaekbote This looks really great! Once there is a decent volume of data the graph rendered will be very impressive.

**Comment by cekbote** [comment]
@yongtang I have added some more CSS elements. I am now working on the backend. Most of the elements are interactive other than the Tabs. Moreover, I still have to add searching using Elasticsearch in this. I'll proably be able to finish this by the weekend. 
I'll keep you updated on the progress. :)

![Dash_App](https://user-images.githubusercontent.com/51071680/84282609-98a9f100-ab57-11ea-8e51-3d21f8ad4e01.PNG)

**Comment by cekbote** [comment]
@yongtang The Application is pretty functional now. A demo can be seen [here](https://github.com/chanakyaekbote/coredns_ml_plugin#visualization-dashboard). Please let me know if there are any more changes I should make. :)
