### ISSUE TITLE
Creating a Manual Vetting Tool

### ISSUE THREAD

**Issue by cekbote** [cekbote/coredns_ml_plugin#8]
@yongtang @greenpau

I have integrated the manual vetting app into the previous dash application. The screenshots can be seen below. So the idea is these lists (not vetted, benign, honeypot, blacklist) are updated in the Elasticsearch server, and then if the domain names are present in the honeypot or blacklist lists, then the flask server directly sends back the address of a honeypot ip or a blackhole ip, and no fallthrough occurs in the go plugin. 

The app screenshots can be seen below, 

App integration:

![App_Integration](https://user-images.githubusercontent.com/51071680/85406297-3a313980-b57f-11ea-932b-a6e889752a2c.PNG)

Manul Vetting:

![Manual_Vetting](https://user-images.githubusercontent.com/51071680/85406319-43baa180-b57f-11ea-8a51-63c123bae855.PNG)

I have to add the functionality of the flask server directly sending back the address of a honeypot ip or a blackhole ip, and no fallthrough occurring in the go plugin. I will work on that once I am done with updating the Readme file and the documentation. (Please see the [weekly goals issue](https://github.com/cekbote/coredns_ml_plugin/issues/7))

Please let me know you're thoughts :)

**Comment by cekbote** [comment]
The application demo can be seen below: 

![manual_vetting](https://user-images.githubusercontent.com/51071680/85550609-c35b7580-b63e-11ea-8e24-1f5f0661a7dd.gif)

Please let me know your thoughts. :)

**Comment by greenpau** [comment]
@cekbote , please use "malicious" instead of "blacklist".

**Comment by cekbote** [comment]
@greenpau Done :)
